#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

datadir = ../../../win32-install-dir
include ./Makefile.am

install:
	if test '$(SUBDIRS)'; then \
	  list='$(SUBDIRS)'; for subdir in $$list; do \
	    $(MAKE) -C $$subdir -f Makefile.mingw install; \
	  done; \
	fi;
	if test '$(gaimsmileypix_DATA)'; then \
	  mkdir -p $(gaimsmileypixdir); \
	  cp $(gaimsmileypix_DATA) $(gaimsmileypixdir); \
	fi;

