#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin pixmaps
#

PIDGIN_TREE_TOP := ../../../..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

datadir = $(PIDGIN_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

install:
	if test '$(pidgintraypix_DATA)'; then \
	  mkdir -p $(pidgintraypixdir); \
	  cp $(pidgintraypix_DATA) $(pidgintraypixdir); \
	fi;

