[Icon Theme]
Name=Pidgin
Comment=Icon theme for Pidgin tray icons
Hidden=True
Directories=16x16/status,22x22/status,32x32/status,48x48/status,scalable/status

[16x16/status]
Size=16
Context=Status
Type=Threshold

[22x22/status]
Size=22
Context=Status
Type=Threshold

[32x32/status]
Size=32
Context=Status
Type=Threshold

[48x48/status]
Size=48
Context=Status
Type=Threshold

[scalable/status]
MinSize=1
Size=128
MaxSize=256
Context=Status
Type=Scalable

