#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

GAIM_TOP = ../../../..
include $(GAIM_TOP)/libpurple/win32/global.mak

datadir = $(GAIM_INSTALL_DIR)
include ./Makefile.am

install:
	if test '$(gaimstatuspix_DATA)'; then \
	  mkdir -p $(gaimstatuspixdir); \
	  cp $(gaimstatuspix_DATA) $(gaimstatuspixdir); \
	fi;

