#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef HAVE_LIBSM
#undef USE_APPLET
#undef USE_GNOME
#undef USE_SCREENSAVER
#undef NO_MULTI
#undef DEBUG
#undef GAIM_PLUGINS
#undef USE_PERL
#undef NAS_SOUND
#undef ESD_SOUND
#undef _REENTRANT
#undef NEED_GNOMESUPPORT_H
#undef NEED_SOCKLEN_T
#undef ZEPHYR_INT32
#undef ZEPHYR_USES_KERBEROS



