#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef HAVE_LIBSM
#undef USE_APPLET
#undef USE_OSCAR
#undef DEBUG
#undef GAIM_PLUGINS
#undef NAS_SOUND
#undef ESD_SOUND
#undef _REENTRANT
#undef NEED_GNOMESUPPORT_H



