#!/usr/bin/perl -w
#
#  gaim
# 
#  Copyright (C) 1998-1999, Mark Spencer <markster@marko.net>
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
#  ---
#
#  Buddy List Conversion Script Written By: John Assalone <assalonej@kpe.com>
#        Modifications by: Rob Flynn <IM: Rob Flynn> <rflynn@blueridge.net>
#
#  Syntax: ./buddytrans buddy.list gaimlist
#

print "Gaim - Buddy List Translator\n";
print "----------------------------\n";

if ((!$ARGV[0]) || (!$ARGV[1]))
{
  print "Syntax: ./buddytrans buddy.lst gaimlist\n";
  exit(0);
}

$source = $ARGV[0];
$dest = $ARGV[1];
if (-e $source)
{
 print("Source=$source, Dest=$dest\n");

 if (-e $dest) 
 {
	print ("$dest exists! Should I continue? ");
	if (<STDIN> =~ /^y/i) 
        { 
          do_trans(); 
        }
	else { exit(0); }
 } 

 do_trans();

sub do_trans {
	open (SOURCE, $source);
	open (DEST, ">$dest");
	print DEST "toc_set_config {m 1\n";
	while ($line = <SOURCE>) {
		chomp($line);
		if ($line =~ /[a-zA-Z]+/) {
			if ($line =~ /^\s/) { $line =~ s/\s//; }
			$line =~ s/\s/\*/;
			($field, $name) = split(/\*/, $line);
			if ($field eq "group") {
				$name =~ s/\"//g;
				print DEST "g $name\n";
				next;
			}
			if ($field eq "buddy") {
				$name =~ s/\"//g;
				print DEST "b $name\n";
				next;
			}
			else { next; }
		}
		else { next; }
	}
	print DEST "}";
}
	print "Conversion Complete.\n";
} else {
  print "Source file must exist!\n\nSyntax: ./buddytrans buddy.lst gaimlist\n";
  exit(0);
}

