#!/bin/bash

# Redirect stdout to a file.
#
# A hack until glib-genmarshal and glib-mkenums work better
# with meson.
#
# Usage:
#   ./redirect "name of output file" ./command to run and args

output=$1
shift
"$@" > $output
exit $?
