#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim sounds
#

GAIM_TOP := ../..
include $(GAIM_TOP)/libpurple/win32/global.mak

datadir := $(GAIM_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

install:
	if test '$(sounds_DATA)'; then \
	  mkdir -p $(soundsdir); \
	  cp $(sounds_DATA) $(soundsdir); \
	fi;

