#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

GAIM_TOP := ../../../..
include $(GAIM_TOP)/libgaim/win32/global.mak

datadir = $(GAIM_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

#Exclude 132k of qq smileys that aren't used on wingaim
install:
	if test '$(gaimsmileypix_DATA)'; then \
	  mkdir -p $(gaimsmileypixdir); \
	  cp $(gaimsmileypix_DATA) $(gaimsmileypixdir); \
	  rm -f $(gaimsmileypixdir)/qq_*; \
	fi;

