# Makefile for creating wave data include files (mingw win32)

all: wav2h.exe hfiles

wav2h.exe:
	gcc -c wav2h.c -o wav2h.o
	gcc -o wav2h.exe wav2h.o

%.h: %.wav wav2h.exe
	./wav2h.exe $<

hfiles: BuddyArrive.h BuddyLeave.h Send.h Receive.h RedAlert.h

clean:
	rm -rf *.o *.exe *.h