#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin ca-certs
#

PIDGIN_TREE_TOP := ../..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

datadir := $(PIDGIN_INSTALL_DIR)
include ./Makefile.am
cacertsdir := $(PIDGIN_INSTALL_DIR)/ca-certs

.PHONY: install

install:
	if test '$(cacerts_DATA)'; then \
	  mkdir -p $(cacertsdir); \
	  cp $(cacerts_DATA) $(cacertsdir); \
	fi;

