/*
 *  wgaimerror.h
 *
 *  Author: Herman Bloggs <hermanator12002@yahoo.com>
 *  Date: October 14, 2002
 *  Description: Redefine Unix Errors
 */

#ifndef _WGAIMERROR_H
#define _WGAIMERROR_H

/* Here we define unix socket errors as windows socket errors */

#define ENETDOWN WSAENETDOWN
#define EAFNOSUPPORT WSAEAFNOSUPPORT
#define EINPROGRESS WSAEINPROGRESS
#define ENOBUFS WSAENOBUFS
#define EPROTONOSUPPORT WSAEPROTONOSUPPORT
#define EPROTOTYPE WSAEPROTOTYPE
#define ESOCKTNOSUPPORT WSAESOCKTNOSUPPORT

#define EADDRINUSE WSAEADDRINUSE
#define EINPROGRESS WSAEINPROGRESS
#define EALREADY WSAEALREADY
#define EADDRNOTAVAIL WSAEADDRNOTAVAIL
#define ECONNREFUSED WSAECONNREFUSED
#define EISCONN WSAEISCONN
#define ENETUNREACH WSAENETUNREACH
#define ENOTSOCK WSAENOTSOCK
#define ETIMEDOUT WSAETIMEDOUT
#define EWOULDBLOCK WSAEWOULDBLOCK

#define ENOTCONN WSAENOTCONN
#define ENETRESET WSAENETRESET
#define EOPNOTSUPP WSAEOPNOTSUPP
#define ESHUTDOWN WSAESHUTDOWN
#define EMSGSIZE WSAEMSGSIZE
#define ECONNABORTED WSAECONNABORTED
#define ECONNRESET WSAECONNRESET

#endif /* end _WGAIMERROR_H */
