#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin pixmaps
#

PIDGIN_TREE_TOP := ../../../..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

datadir = $(PIDGIN_INSTALL_DIR)
include ./Makefile.am

.PHONY: install clean

install: theme
	if test '$(pidginsmileypix_DATA)'; then \
	  mkdir -p $(pidginsmileypixdir); \
	  cp $(pidginsmileypix_DATA) $(pidginsmileypixdir); \
	fi;

clean:
	rm -f theme

