#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin pixmaps
#

GAIM_TOP := ../../../..
include $(GAIM_TOP)/libpurple/win32/global.mak

datadir = $(GAIM_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

install:
	if test '$(gaimsmileypix_DATA)'; then \
	  mkdir -p $(gaimsmileypixdir); \
	  cp $(gaimsmileypix_DATA) $(gaimsmileypixdir); \
	fi;

