#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

GAIM_TOP = ../../..

INSTALL_DIR = $(GAIM_TOP)/win32-install-dir/pixmaps/gaim/smileys

include ./Makefile.am

install:
	if test '$(SUBDIRS)'; then \
	  list='$(SUBDIRS)'; for subdir in $$list; do \
	    $(MAKE) -C $$subdir -f Makefile.mingw install; \
	  done; \
	fi;
