#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

INSTALL_DIR = ../../../win32-install-dir/pixmaps/gaim/protocols/gg

include ./Makefile.am

install:
	if test '$(SUBDIRS)'; then \
	  list='$(SUBDIRS)'; for subdir in $$list; do \
	    $(MAKE) -C $$subdir -f Makefile.mingw install; \
	  done; \
	fi;
	if test '$(EXTRA_DIST)'; then \
	  mkdir -p $(INSTALL_DIR); \
	  cp $(EXTRA_DIST) $(INSTALL_DIR); \
	fi;

