.\" Copyright (c) 2000, Dennis Ristuccia <dennis@vertex.978.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.TH GAIM 1
.SH NAME
gaim v0.11.0pre13 \- Instant Messaging client
.SH SYNOPSIS
.TP 5
\fBgaim \fI[options]\fR

.SH DESCRIPTION
.PP
\fBgaim\fR is an Instant Messaging (IM) client designed primarily for use with AOL Instant Messager (AIM).  However, it supports most other popular IM protocols including ICQ, MSN Messager, Jabber, Yahoo!, IRC, Napster, and Zephyr. 

.SH OPTIONS
The following options are provided by \fBgaim\fR using the standard GNU command line syntax.
.TP
.B \-a, \-\-acct
Launch the \fBaccount editor\fR rather than the login window on start.
.TP
.B \-w, \-\-away[=MESG]
Automatically go away on signon.  You may optionally use the MESG parameter to set the away message.
.TP
.B \-l, \-\-login[=NAME]
Automatically login on start using the default account or the account specified by the NAME parameter.
.TP
.B \-u, \-\-user=NAME
Use account NAME as default.
.TP
.B \-f, \-\-file=FILE
Use FILE as the configuration file instead of ~/.gaimrc.

.SH BUDDY LIST
The \fBBuddy List Window\fR is \fBgaim\fR's main interface window.  The focus of this window is the \fBBuddy List\fR itself.  This is a list of your contacts whose presence you have been notified of.

The list of buddies is organized into groups.  \fBGaim\fR supports multiple connections, but all online buddies are organized on the same buddy list.  Buddy List organization is handled in the \fBEdit Buddies\fR tab.

Buddy Lists can be imported and exported to disk using the appropriate commands in the \fIfile\fR menu.

The icon to the left of each buddy indicates the buddy's current state.  Double clicking a buddy will open a new \fBconversation window\fR.  Right clicking will open a menu:
.TP
.B IM
Opens a new \fBconversation window\fR to the selected buddy.
.TP
.B Alias
Create an alias for this buddy.  This will open up a new dialog in which one can give this buddy an alternate name to appear on the buddy list and in conversataions.

For example, if a buddy's name screen name was jsmith1281xx and his real name was 'John Q. Smith,' one could create an alias as to identify the buddy by his common name. 
.TP
.B Add Buddy Pounce
A Buddy Pounce is a configurable automated action to be performed when the buddy's state changes.  This will open the \fBBuddy Pounce\fR dialog to be discussed later.
.TP 
.B View Log
\fBgaim\fR is capable of automatically log its activities.  These logs are html files (with a .log extenstion) located in the ~/.gaim/logs directory.  This menu command will attempt to view this file with \fBgaim's\fR internal log viewer.
.LP
The remainder of the menu will consist of protocol specific commands.  If logged on with multiple connections, these will appear in submenus named with each screen name logged on.  These commands vary depending on the protocol; below are the commands available when using OSCAR, the more popular and developer-recommended AIM protocol:
.TP
.B Get Info
Retrieves and displays information about the buddy.  This information is also known as a Profile.
.TP
.B Get Away Msg
If this buddy is in an Away state, this will retrieve and display the buddy's \fBAway Message\fR.
.TP
.B Direct IM
This will send a request to the buddy for a \fBDirect IM\fR.  If accepted, a direct connection will be made between the two clients, no longer relying on the server.  This will reveal your IP address to your buddy, which may constitute a security risk.

.SH The Conversation Window
When starting a new conversation, the user is presented with the conversation window.  The conversation appears in the upper text box and the user types his message in the lower.  Between the two is a row of setting, represented by icons.  From left to right:
.TP
.B Bold
adds <b></b> to your message
.TP
.B Italics
adds <i></i> to your message
.TP
.B Underline
adds <u></u> to your message
.TP
.B Strikethrough
adds <s></s> to your message
.TP
.B Decrease font size
adds <font size="1"></font> to your message
.TP
.B Default font size
adds <font size="3"></font> to your message
.TP
.B Increase font size
adds <font size="5"></font> to your message
.TP
.B Select font face
adds an appropriate font tag to your message.
.TP
.B Select a foreground color
adds an appropriate font tag to your message.
.TP
.B Select a background color
adds an appropriate body tag to your message.
.TP
.B Add hyperlink
adds an appropriate a href tag to your message.
.TP
.B Add smiley
adds an ASCII smiley to your message.  This will become a graphic smiley in the upper textbox if the option for graphical smileys is set.
.TP
.B Enable logging
As the conversation continues, everything will get logged to a log file in ~/.gaim/logs
.TP
.B Save Conversation
Saves the current conversation to a log file of your choice.
.TP
.B Enable Sounds
Choose whether events in this conversation will trigger sounds.

Beneath the lower textbox is a row of buttons that execute commands:
.TP
.B Send
This sends what's currently in the lower textbox
.TP
.B Get Info
This gets information (a profile) about the other person in the conversation.
.TP
.B Warn
This issues a warning to the other person in the conversation.
.TP
.B Block
This adds the other person to your deny list.
.TP
.B Add to buddy list
This adds this user to your buddy list.  If he already is on your list, it will remove him from it.
.TP
.B Close
Closes this window.


.SH Edit Buddies
Clicking this tab on the \fBBuddy List Window\fR will invoke the main interface to edit and organize buddy lists.  Buddy's already in your buddy list can be moved to different groups or reordered in the same group by clicking and dragging with the mouse.  One can also add, rename, alias, or delete buddies here, as well as some of the functions available in the \fBBuddy List Dialog\fR.  

In the \fBEdit Buddies\fR dialog, the list is arranged by connection.  If two or more connections have a group of the same, the \fBBuddy List\fR will only show one group with that name.  Available buddies from \fIboth\fR connections will be shown in this group.  If both connections have a buddy with the same screen name in a group of the same name, the buddy will appear only once.

.SH Buddy Chat
For protocols that allow it, \fBBuddy Chats\fR can be entered through the file menu, the keyboard shortcut \fICTRL+C\fR, or the right most button on the bottom of the \bBBuddy List Dialog\fR.

Additional commands available in chat, depending on the protocol are:
.TP
.B Whisper
The text will appear in the chat conversation, but it will only be visible to the sender and the receiver.
.TP
.B Invite
Invite other people to join the chat room.
.TP
.B Ignore
Ignore anything said by the chosen person
.TP
.B Set Topic
Set the topic of the chat room.  This is usually a brief sentence describing the nature of the chat--an explanation of the chat room's name.

.SH AWAY MESSAGES
Most protocols allow for away messages.  When a user is \fIaway\fR, he can leave a message indicating why for others to see.  The \fBaway\fR submenu of the \fBTools\fR menu is used to add and remove away message, as well as to set a user's away state.

\fINew Away Message\fR provides space for one to enter an away message and a title for that message.  If \fISave\fR of \fISave & Use\fR are chosen, this message will be saved.  It can later be referred to by the title given to it.

\fIRemove Away Message\fR is a submenu containing the titles of saved away messages.  Clicking on one of these titles will remove the away message associated with it.

The rest of the \fIaway\fR menu provides the user with a way to assign different away messages to different connections.  Choosing \fISet All Away\fR will set away all the connections capable of the away state.

.SH BUDDY POUNCE
A Buddy Pounce is an automated trigger that occurs when a buddy returns to a normal state from an away state.  A pounce can be set to occur on any combination of the events listed, and any combination of actions can result.  If \fISave this pounce after activation\fR is checked, the trigger will remain until it is removed from the \fIRemove buddy pounce\fR menu.

.SH ACCOUNT EDITOR
The account editor consists of a list of accounts and information about them.  Clicking \fIAdd\fR or \fIModify\fR will invoke a \fIModify Account\fR window.  Here, you can alter information about your account.  When creating a new account, you will submit your screen name and password.  You will also choose your protocol; The two AIM protocols, TOC and OSCAR are always loaded, but other protocols can be dynamically loaded and unloaded using \fBProtocols Plugins (PRPLS)\fR.  

If \fBRemember Password\fR is chosen, the password will be saved in \fBgaim's\fR configuration file.

If \fBAuto-Login\fR is chosen, this account will automatically login upon starting \fBgaim\fR.

Each protocol has it's own specific options that can be found in the protocol-specific tab on the modify screen.

.SH PERL
/fBGaim/fR allows for perl scripting.  This submenu provides for the loading of individual perl scripts and for the unloading of all of them.  See PERL-HOWTO for more information about perl scripting.

.SH PLUGINS
/fBGain/fR allows for dynamic loading of plugins.  The plugin window shows the paths to loaded plugins on the left, and the name and description of the plugin on the right.

You may load and unload plugins using the appropriate buttons.

.SH PREFERENCES
.SH General
.TP
.B Use Borderless Buttons
Change the appearence of the GUI's buttons.
.TP
.B Show Buddy Ticker
This opens the \fBBuddy Ticker\fR, a small window in which the contents of your buddy list scroll to keep you up to date on their status.
.TP
.B Show Debug Window
This opens a debug window into which \fBgaim\fR sends more verbose information about what it's doing.
.TP
.B Report Idle Times
For protocol's that require the client to report idle times, this option sets the method of determining idle times.  If \fINone\fR is chosen, idleness will not be reported.  If \fIGAIM Use\fR is chosen, it will send idle times relative to the last time \fBgaim\fR was used.  If \fIX Use\fR is chosen, idle times will be reported based on the last time the mouse or keyboard was used.
.TP
.B Logging
Log all conversations will automatically log conversations into ~/.gaim/logs/.  Unless \fIStrip HTML from logs\fR is checked, they will be saved as an HTML file with a .log extension.  The preferences window provides options to specify exactly what to log.
.TP
.B Browser
Choose the Web Browser to use when a hyperlink is clicked.
.SH Buddy List
.TP
.B Hide IM/Info/Chat buttons
This option will remove the three buttons beneath the \fBBuddy List\fR in the \fBBuddy List Window\fR.
.TP
.B Show pictures on buttons
If checked, the buttons will feature an icon, otherwise, the buttons will be text.
.TP
.B Hide groups with no online buddies
This feature will only display a folder representing a group if there is at least one online buddy in it.
.TP
.B Shoe numbers in groups
This feature displays the number of buddies in each group and the number of these online in the \fBBuddy List\fR.
.TP
.B Show buddy type icons
This icon is a quick reference as to what protocol a buddy is using, and what away state, if any, he is in.
.TP
.B Show Idle times
This shows how long a buddy has been idle next to his name.
.B Show warning levels
This shows the warning level of a buddy next to his name.
.SH Conversations
.TP
.B Keyboard Options
These options set certain keybindings.
.TP
.B Show graphical smileys
This will convert emoticons such as :) and >:-O to small icons representing them.
.TP
.B Show timestamp on messages
When selected, this option shows in the conversation window, the time each message was received or sent.
.TP
.B Show URLs as links
This will convert URLs such as http://gaim.sourceforge.net to a hyperlink pointing to that site.
.TP
.B Highlight misspelled words
While typing a message, if a user misspells a word, it will immediately turn red.  Right-clicking on the word will invoke a menu of possible corrections.
.TP
.B Sending messages removes away status
If this option is selected, a user will come back from \fBaway\fR if he sends a message to someone.
.TP
.B Queue new messages when away
This option will cause new conversation windows not to be created until a user returns from away.  Instead, a record of how many messages received and from whom they were received is shown in the away message window.
.TP
.B Ignore colors/font faces/ font sizes
These options ignore font settings that can be set in HTML tags.
.TP
.B Ignore TiK Automated Messages
AOL's open source TiK client gets a user's away message by sending him an automated message.  This option ignores those messages.
.TP
.B Ignore new conversations when away
If checked, new conversations will be ignored entirely when away.  Unlike the \fBQueue new messages when away\fR option, no record will be kept of these.
.SH Windows
.TP 
.B Show buttons as:
This option selects the look of the buttons.
.TP
.B Show all conversations in one tabbed window
Instead of seperate windows for each conversation, they are all shown in one window with tabs at the top to select the conversation.  A name on a tab will become red if a new message hasn't yet been read.
.TP
.B Raise windows on events
When an event happens to a conversation, the conversation window will be raised above all other windows on the desktop.
.TP
.B Show logins in window
This will show when buddies log in and out in the conversation window, if one is open for that buddy.
.TP
.B Window size
Select the default size for new conversation windows.
.SH Font Options
.TP 
 These set the font preferences that are sent with all messages over a protocol that supports HTML.
.SH Chat Rooms
.TP
This is a list of available chat rooms and chat rooms that you are subscribed to.
.SH Sounds
.TP
.B No sounds when you log in
This will prevent sounds from playing when \fBgaim\fR is first notified of your buddy's presence because you just signed on.
.TP
.B Sounds while away
This option will continue to play sounds on events if you are away.
.TP
.B Beep instead of playing sound
This will cause a terminal beep instead of a sound upon events.
.TP
.B Command to play sound files
If you need a special command executed to play a sound, enter it in the given box with %s representing the filename.  If you prefer \fBgaim\fR to play the sound, leave it blank.
.TP
.B Events
Choose sounds to play when each event occurs.
.SH Away Messages
.TP
.B Don't send auto-response
If someone sends the user a message while away, \fBgaim\fR will not respond with the away message if this is checked.
.TP
.B Auto Away
If this is selected \fBgaim\fR will automatically go away if it's been idle for the specified length of time.
.SH Privacy
.TP
Here, the user can configure his permit/deny lists.



.SH FILES
~/.gaimrc \- Gaim Config File
.br
~/.gaim/logs/SCREENNAME.log \- a log of all conversation with SCREENNAME.
.br
/usr/local/lib/gaim/ \- Gaim Plugin Files
.br
~/.gaim/SCREENAME.PROTOCOL.blist \- the buddy list for SCREENAME using protocol number PROTOCOL
.SH BUGS
Known bugs are at http://sourceforge.net/bugs/?group_id=235
.SH BUG REPORTS
If you find a bug in \fBgaim\fR, please submit a bug form at
http://sourceforge.net/bugs/?group_id=235
.PP
Before sending a bug report, please verify that you have the latest 
version of \fBgaim\fR.  Many bugs (major and minor) are fixed 
at each release, and if yours is out of date, the problem may already 
have been solved.

.SH SEE ALSO
\fIhttp://gaim.sourceforge.net/\fR
\fIhttp://www.sourceforge.net/projects/gaim/\fR

.SH LICENSE
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
\fBWITHOUT ANY WARRANTY\fR; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple PLace, Suite 330, Boston, MA  02111-1307  USA
.SH AUTHORS
The authors of \fBgaim\fR are:
.PP
 Rob Flynn <rob@marko.net> \- AIM: RobFlynn
.br
 Eric Warmenhoven <warmenhoven@yahoo.com> \- AIM: EWarmenhoven
.br
 Syd Logan

The retired authors of \fBgaim\fR are:
.PP
 Jim Duchek <jim@linuxpimps.com> \- AIM: Zilding
.br
 Mark Spencer <markster@marko.net> \- AIM: Markster97


.PP

This manpage was originally written by Dennis Ristuccia <dennis@vertex.978.org> AIM: D3nnisR.  It has been updated and largely rewritten by Sean Egan <sean@posseweb.org> AIM: SeanEgn

.\" WOO!
.\" Agreed, Dennis, agreed.
