#
# Makefile.mingw
#
# Description: Makefile for perl plugin loader plugin.
#

GAIM_TOP := ../../..
include $(GAIM_TOP)/libpurple/win32/global.mak

##
## TARGET DEFINITIONS
##
.PHONY: all install clean

all:
	$(MAKE) -C ./common -f $(GAIM_WIN32_MAKEFILE)

install: all $(GAIM_INSTALL_PLUGINS_DIR)
	$(MAKE) -C ./common -f $(GAIM_WIN32_MAKEFILE) install

##
## CLEAN RULES
##
clean:
	$(MAKE) -C ./common -f $(GAIM_WIN32_MAKEFILE) clean
