#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version
#

PIDGIN_TREE_TOP := ..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

include ./Makefile.am

.PHONY: install clean

install:
	if test '$(SUBDIRS)'; then \
	  list='$(SUBDIRS)'; for subdir in $$list; do \
	    $(MAKE) -C $$subdir -f $(MINGW_MAKEFILE) install || exit 1 ;\
	  done; \
	fi;
