#
## Makefile.mingw
#
## Description: Makefile for win32 (mingw) version of Gaim QQ buddy icons
#
#

GAIM_TOP = ../../../..
include $(GAIM_TOP)/libpurple/win32/global.mak

datadir = $(GAIM_INSTALL_DIR)
include ./Makefile.am

install:
	if test '$(qqbuddyiconspix_DATA)'; then \
	  mkdir -p $(qqbuddyiconspixdir); \
	  cp $(qqbuddyiconspix_DATA) $(qqbuddyiconspixdir); \
	fi;
