#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin pixmaps
#

include ./Makefile.am

install:

install_real:
	if test '$(SUBDIRS)'; then \
	  list='$(SUBDIRS)'; for subdir in $$list; do \
	  if [ "$$subdir" != "22" ]; then \
	    $(MAKE) -C $$subdir -f Makefile.mingw install || exit 1; \
	  fi; \
	  done; \
	fi;

