#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Gaim pixmaps
#

GAIM_TOP = ../../../..
include $(GAIM_TOP)/libgaim/win32/global.mak

datadir = $(GAIM_INSTALL_DIR)
include ./Makefile.am

#Exclude 264k of qq icons that aren't used on wingaim
install:
	if test '$(gaimstatuspix_DATA)'; then \
	  mkdir -p $(gaimstatuspixdir); \
	  cp $(gaimstatuspix_DATA) $(gaimstatuspixdir); \
	  rm -f $(gaimstatuspixdir)/qq*; \
	fi;

