#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin sounds
#

PIDGIN_TREE_TOP := ../..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

datadir := $(PIDGIN_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

install:
	if test '$(sounds_DATA)'; then \
	  mkdir -p $(soundsdir); \
	  cp $(sounds_DATA) $(soundsdir); \
	fi;

